manager/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("requests", views.requests, name="requests"),
    path("hr_view", views.hr_view, name="hr_view"),
    path(
        "manager_view_monthly", views.manager_view_monthly, name="manager_view_monthly"
    ),
    path("manager_view_total", views.manager_view_total, name="manager_view_total"),
]

vacation_planner/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("employee_dashboard.urls")),
    path("admin/", admin.site.urls),
    path("", include("vacations.urls")),
    path("", include("employees.urls")),
    path("manager/", include("manager.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

vacations/models.py
import datetime

from django.db import models

from employees.models import City, Employee


class VacationDay(models.Model):
    TYPE_CHOICES = ((1, "Vacation"), (2, "Special leave"))
    employee = models.ForeignKey(
        Employee, on_delete=models.CASCADE, related_name="vacation_days"
    )
    date = models.DateField()

    # An employee can have half a day off, by default it a full day
    # A full day is 1; a half day is 0.5
    FULL_DAY_CHOICES = (
        (1.0, "1.0"),
        (0.5, "0.5"),
    )

    duration = models.DecimalField(
        default=1,
        max_digits=2,
        decimal_places=1,
        choices=FULL_DAY_CHOICES,
    )
    approved = models.BooleanField(default=False)
    type = models.IntegerField(choices=TYPE_CHOICES, default=1)
    # Description is needed only if it's a special leave
    # Is disabled when it's a regular vacation
    description = models.CharField(max_length=200, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)


class PublicHolidays(models.Model):
    date = models.DateField()
    name = models.CharField(max_length=100, null=True, blank=True)
    cities = models.ManyToManyField(City)
    every_year = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Public holidays"


# TODO: rename AvailableDay. Use singular names, not plural, for model names
class AvailableDays(models.Model):
    employee = models.ForeignKey(
        Employee, on_delete=models.CASCADE, related_name="available_days"
    )
    allotted_days = models.DecimalField(max_digits=3, decimal_places=1, default=30.0)
    transferred_days = models.IntegerField(default=0)
    remote_work_days = models.IntegerField(default=30)
    # TODO: make sure this is the year in which
    year = models.IntegerField(default=datetime.datetime.now().year, editable=True)

    def __str__(self):
        return f"{self.employee} {self.transferred_days}"

    class Meta:
        verbose_name_plural = "Available days"
        unique_together = ["employee", "year"]


class Request(models.Model):
    TYPES = ((1, "vacation"), (2, "transfer"), (3, "cancel"), (4, "remote_work"))
    STATUS_OPTIONS = ((1, "pending"), (2, "approved"), (3, "rejected"))

    employee = models.ForeignKey(
        Employee, on_delete=models.CASCADE, related_name="requests"
    )
    start_date = models.DateField()
    end_date = models.DateField()
    description = models.TextField(max_length=200, null=True, blank=True)
    request_type = models.IntegerField(choices=TYPES, default=1)
    request_status = models.IntegerField(choices=STATUS_OPTIONS, default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)


class RemoteDay(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    date = models.DateField()
    description = models.TextField(max_length=200, null=True, blank=True)
    approved = models.BooleanField(default=False)

templates/employee_view/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Your Vacation</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" /> 
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <link rel="stylesheet" href="{% static 'css/calendar_main.css' %}" />
    <link rel="stylesheet" href="{% static 'css/calendar.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />

    {% block extracss %}{% endblock %}
  </head>
  <body>
    <!-- Top Bar -->

    <div class="topbar container row justify-content-between">
      <div class="left col-4">
        <span class="nav-user-name" style="margin: 0 20px">
          {% if user.is_authenticated %}
            <h2>Hello, {{ user.first_name }}</h2>
          {% else %}
            <h2>Hello, Guest</h2>
          {% endif %}
        </span>
      </div>
        <div class="right col-4 d-flex justify-content-end">
          <!-- <a href="../logout.html" class="logout-btn">Log out</a> -->
          <div class="container">
            <!-- TODO: clear cookies after clicking log out -->
            <a href="javascript:{document.getElementById('logout').submit()}" 
            class="logout-btn btn btn-secondary btn-block col-md-6">Log out</a>
            <form action="{% url 'logout' %}" method="POST" id="logout">
              {% csrf_token %}
              <input type="hidden">
            </form>
         </div>
        </div>
      </div>
    </div>


    <!-- Left Side -->
    <div class="leftside">
        <div class="logo">
          <a href="{% url 'calendar' %}">
            <span>
              <img
                src="{% static 'images/systemverification_logo.png' %}"
                alt="logo-large"
                class="logo"
              />
            </span>
          </a>
        </div>
        <div class="leftside-menu">
          <ul>
            <li 
              {% if '/' == request.path %}
                class="menu-item active-link"
              {% else %}
                class="menu-item"
              {% endif %}
              >
              <a href="{% url 'calendar' %}">
                <i class="fa-solid fa-calendar-days" style="color: #ffffff"></i>Calendar
              </a>
            </li>
            <li 
            {% if '/dashboard' == request.path %}
              class="menu-item active-link"
            {% else %}
              class="menu-item"
            {% endif %}
            >
              <a href="{% url 'dashboard' %}">
                <i class="fa-solid fa-eye" style="color: #ffffff"></i>
                Dashboard
              </a>
            </li>
            <li
            {% if '/vacation_request' == request.path %}
              class="menu-item active-link"
            {% else %}
              class="menu-item"
            {% endif %}>
              <a href="{% url 'vacation_request' %}">
                <i class="fa-solid fa-plus" style="color: #ffffff"></i>
                Vacation request
              </a>
            </li>
            <li
            {% if '/transfer_days_request' == request.path %}
              class="menu-item active-link"
            {% else %}
              class="menu-item"
            {% endif %}>
              <a href="{% url 'transfer_days_request' %}">
                <i class="fa-solid fa-arrow-down-up-across-line" style="color: #ffffff"></i>
                Transfer days
              </a>
            </li>
            <li
            {% if '/cancel_vacation_days' == request.path %}
              class="menu-item active-link"
            {% else %}
              class="menu-item"
            {% endif %}>
              <a href="{% url 'cancel_vacation_days' %}">
                <i class="fa-solid fa-trash-can" style="color: #ffffff"></i>
                Cancel vacation days
              </a>
            </li>
            <li
            {% if '/remote_work_request' == request.path %}
              class="menu-item active-link"
            {% else %}
              class="menu-item"
            {% endif %}>
              <a href="{% url 'remote_work_request' %}">
                <i class="fa-solid fa-house-laptop" style="color: #ffffff"></i>
                Request remote work
              </a>
            </li>
            <!-- Add jinja to show the button only to managers -->
            {% if request.user.employee.is_manager %}
            <li class="menu-item">
              <a href="{% url 'hr_view' %}" target="_blank">
                <i class="fa-solid fa-eye" style="color: #ffffff"></i>
                Manager View
              </a>
            </li>
            {% endif %}
          </ul>
        </div>
    </div>

    <!-- Main BLock -->
    {% block content %} {% endblock %}

    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script 
    src="https://kit.fontawesome.com/65d2e5b72d.js"
    crossorigin="anonymous"
  ></script>
  {% block extrascripts %}{% endblock %}
  </body>
</html>

templates/employee_view/calendar.html
{% extends 'employee_view/base.html' %}
{% load static %}

{% block extracss %}
<link rel="stylesheet" href="{% static 'calendar/main.css' %}" />
{% endblock extracss %}

{% block content %} 

<div class="main">
  <div class="main-top">
    <ul>
      <span>Calendar</span>
      <span>Year</span>
      <i class="fa-solid fa-angle-up" style="color: #292b2c"></i>
      <span>2023</span>
      <i class="fa-solid fa-angle-down" style="color: #292b2c"></i>
    </ul>
  </div>

  <!-- Calendar -->
  <div class="Calendar container">
    <div class="row justify-content-center">
      <div class="col-md-10">
        <div class="tile row">
          <div class="col-md-3">
            <div id="external-events">
              <h4 class="mb-4">Events</h4>
              <p>No Events Found</p>
              <!-- TODO: make it work -->
              <!-- {% for event in events_month %}
              <div class="fc-event">
                <h3>{{ event.title }}</h3>
                <p>From: {{ event.start_time }}</p>
                <p>To: {{ event.end_time }}</p>
              </div>
              {% empty %}
              <p>No Running Events Found</p>
              {% endfor %} -->
            </div>
          </div>
          <div class="col-md-9">
            <div id="calendar"></div>
          </div>

          <div
            class="modal fade show"
            id="eventModal"
            tabindex="-1"
            role="dialog"
            aria-labelledby="exampleModalCenterTitle"
            aria-hidden="true"
          >
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header bg-primary">
                  <h5 class="modal-title text-white" id="exampleModalLongTitle">
                    Add New Event
                  </h5>
                  <button
                    id="modalClose1"
                    type="button"
                    class="close"
                    data-dismiss="modal"
                    aria-label="Close"
                  >
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block extrascripts %}
<script src="{% static 'js/main-calendar.js' %}"></script>
<script>
  document.addEventListener("DOMContentLoaded", function () {
    var calendarEl = document.getElementById("calendar");
    var today = new Date();

    var calendar = new FullCalendar.Calendar(calendarEl, {
      headerToolbar: {
        left: "prev,next today",
        center: "title",
        right: "dayGridMonth,timeGridWeek,timeGridDay,list",
      },
      initialDate: today,
      navLinks: true, // can click day/week names to navigate views
      selectable: true,
      selectMirror: true,
      select: function (arg) {
        console.log("clicked");
        var modal = document.getElementById("eventModal");
        modal.style.display = "block";
        calendar.unselect();
      },
      // THIS KEY WON'T WORK IN PRODUCTION!!!
      // To make your own Google API key, follow the directions here:
      // http://fullcalendar.io/docs/google_calendar/
      // googleCalendarApiKey: 'AIzaSyCqCxjjLtjbtkX37aOtWB8OfwBLy_6QuYk',

      // bangladesh Holidays
      // events: 'bn.bd#holiday@group.v.calendar.google.com',
      eventClick: function (arg) {
        if (confirm("Are you sure you want to delete this event?")) {
          arg.event.remove();
        }
      },
      editable: true,
      dayMaxEvents: true,
      //add jinja
      events: [],
    });

    calendar.render();
  });
  const closeBtn1 = document.getElementById("modalClose1");
  const closeBtn2 = document.getElementById("modalClose2");
  closeBtn1.addEventListener("click", () => {
    const eventModal = document.getElementById("eventModal");
    eventModal.style.display = "none";
  });
  closeBtn2.addEventListener("click", () => {
    const eventModal = document.getElementById("eventModal");
    eventModal.style.display = "none";
  });
  src = "https://kit.fontawesome.com/65d2e5b72d.js";
  crossorigin = "anonymous";
</script>
{% endblock extrascripts %}

templates/employee_view/cancel_vacation_days.html
{% extends 'employee_view/base.html' %} {% block content %}
<div class="container">
  <div class="row text-center">
    <div class="col-md-12">
      <div id="alert-container"></div>

      <!-- Alerts -->
      {% include '_alerts.html' %}
      <form
        id="vacation-form"
        action="{% url 'cancel_vacation_days'  %}"
        method="POST"
      >
        {% csrf_token %}
        <div class="alert-container"></div>
        <div class="form-group row">
          <label for="start_date" class="col-sm-2 col-form-label"
            >Start Date</label
          >
          <div class="col-sm-4">
            <div class="form-group">
              <div class="input-group date" id="startdate">
                <input
                  type="date"
                  class="form-control"
                  name="startdate"
                  required
                />
                <span class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
                </span>
              </div>
            </div>
          </div>
        </div>

        <div class="form-group row">
          <label for="enddate" class="col-sm-2 col-form-label">End Date</label>
          <div class="col-sm-4">
            <div class="form-group">
              <div class="input-group date" id="enddate">
                <input
                  type="date"
                  class="form-control"
                  name="enddate"
                  required
                />
                <span class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
                </span>
              </div>
            </div>
          </div>
        </div>
        <div class="form-group row">
          <label for="start_date" class="col-sm-2 col-form-label"
            >Description</label
          >
          <div class="col-sm-4">
            <div class="form-group">
              <div class="input-group description" id="description">
                <input type="text" class="form-control" />
              </div>
            </div>
          </div>
        </div>
        <button class="btn btn-secondary mt-4" type="submit">Save</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/employee_view/dashboard.html
{% extends 'employee_view/base.html' %} {% block content %}
<div class="container">
  <div class="container">
    <form         
    id="year-form"
    action="{% url 'dashboard'  %}"
    method="POST"
    >
    {% csrf_token %}
      <div class="row">
        <div class="col-md-2 align-self-center">
          <select name="year" class="form-control">
            <option selected="true" disabled="disabled">
              {{current_year}}
            </option>
            {% for  year in years %}
            <option value="{{ year }}">{{ year }}</option>
            {% endfor %}
          </select>
        </div>
        <div class="col-md-2 align-self-center">
          <button class="btn btn-secondary btn-block" type="submit">
            Submit
          </button>
        </div>
      </div>
    </form>
  </div>

  <div class="container">
    <table class="table" style="margin: 10px 0 20px 0">
      <thead>
        <tr>
          <th scope="col">Used, planned or requested this year</th>
          <th scope="col">Allotted days for this</th>
          <th scope="col">Transferred days for this year</th>
          <th scope="col">Days left this year</th>
          <th scope="col">Usage</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="text-center">{{ num_of_vac_days }}</td>
          <td class="text-center">{{ num_of_alloted_days }}</td>
          <td class="text-center">{{ num_of_transferred_days }}</td>
          <td class="text-center">{{ days_left_this_year }}</td>
          <td class="text-center">
            {{ usage }}%
            <div class="progress progress-striped">
              <div
                class="bar"
                style="width: {{ usage }}%; background-color: black"
              ></div>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="container">
    <table class="table" style="margin: 10px 0">
      <thead>
        <tr>
          <th scope="col">From</th>
          <th scope="col">Till</th>
          <th scope="col">Request type</th>
          <th scope="col">Request Status</th>
          <th scope="col">Requested</th>
          <th scope="col">Description</th>
        </tr>
      </thead>
      <tbody>
        {% for request in all_requests%}
        <tr>
          <td>{{ request.start_date }}</td>
          <td>{{ request.end_date }}</td>
          <td>{{ request.get_request_type_display }}</td>
          <td>{{ request.get_request_status_display }}</td>
          <td>{{ request.created_at|date:"d-m-Y" }}</td>
          <td>{{ request.description }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}

templates/employee_view/login.html
{% extends 'employee_view/register_login_base.html' %}
{% load static %}
{% block content %} 
  <div class="form-holder">
            <div class="form-content">
              <div class="form-items">
                <h2>System Verification </h2>
                <h3>Vacation App</h3>
                <p>Login</p>
                <div class="page-links">
                  <a href="{% url 'login' %}" class="active">Login</a
                  ><a href="{% url 'register' %}">Register</a>
                </div>
                <!-- Alerts -->
                {% include '_alerts.html' %}
                <form action="{% url 'login'  %}" method="POST">
                  {% csrf_token %}
                  <input
                    class="form-control"
                    type="text"
                    name="email"
                    placeholder="E-mail Address"
                    required
                  />
                  <input
                    class="form-control"
                    type="password"
                    name="password"
                    placeholder="Password"
                    required
                  />
                  <div class="form-button">
                    <button id="submit" type="submit" class="ibtn">Login</button>
                    <a href="forget4.html">Forget password?</a>
                  </div>
                </form>
                <div class="other-links">
                  <span>Or login with</span><a href="#">Facebook</a
                  ><a href="#">Google</a><a href="#">Linkedin</a>
                </div>
              </div>
            </div>
  </div>
{% endblock %}

templates/employee_view/register.html
{% extends 'employee_view/register_login_base.html' %} {% load static %} 
{% block content %}
<div class="form-holder">
  <div class="form-content">
    <div class="form-items">
      <h2>System Verification </h2>
      <h3>Vacation App</h3>
      <p>Register</p>

      <div class="page-links">
        <a href="{% url 'login' %}">Login</a
        ><a href="{% url 'register' %}" class="active">Register</a>
      </div>
      <!-- Alerts -->
      {% include '_alerts.html' %}
      <form action="{% url 'register'  %}" method="POST">
        {% csrf_token %}
        <input
          class="form-control"
          type="text"
          name="first_name"
          placeholder="Name"
          required
        />
        <input
          class="form-control"
          type="text"
          name="last_name"
          placeholder="Surname"
          required
        />
        <input
          class="form-control"
          type="email"
          name="email"
          placeholder="E-mail Address"
          required
        />

        <input
          class="form-control"
          type="password"
          name="password"
          placeholder="Password"
          required
        />
        <input
          class="form-control"
          type="password"
          name="password2"
          placeholder="Password"
          required
        />
        <div class="col-md-12 mb-2" style="padding: 0" required>
          <label class="">Choose your city</label>
          <select id="city" name="city" class="form-control" required>
            {% for city in cities %}
            <option value="{{ city.name }}">{{ city.name }}</option>
            {% endfor %}
          </select>
        </div>
        <div class="col-md-12 mb-2" style="padding: 0">
          <label class="">Choose your manager</label>
          <select name="manager" class="form-control" required>
            {% for manager in managers %}
            <option value="{{ manager.user.id }}">
              {{ manager.user.first_name }} {{ manager.user.last_name }}
            </option>
            {% endfor %}
          </select>
        </div>
        <div class="col-md-12 mb-2" style="padding: 0">
          <label class="">Working since</label>
          <div class="input-group date" id="enddate">
            <input
              type="date"
              class="form-control"
              name="start_date"
              required
            />
            <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
        </div>
        <div class="col-md-12 mb-2" style="padding: 0">
          <label class="">Your employment type</label>
          <select id="city" name="employment_type" class="form-control" required>
            <option value="1">Full-time</option>
            <option value="2">Other</option>
          </select>
        </div>
        <div class="form-button">
          <button id="submit" type="submit" class="ibtn">Register</button>
        </div>
      </form>
      <div class="other-links">
        <span>Or register with</span><a href="#">Facebook</a
        ><a href="#">Google</a><a href="#">Linkedin</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/employee_view/register_login_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap2.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/iofrm-style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/iofrm-theme4.css' %}" />
  </head>
  <body>
    <div class="form-body">
      <div class="website-logo">
          <div class="logo">
            <img
              src="{% static 'images/systemverification_logo_black.png' %}"
              alt=""
            />
          </div>
        </a>
      </div>
      <div class="row">
        <div class="img-holder">
          <div class="bg"></div>
          <div class="info-holder">
            <img src="{% static 'images/graphic1.svg' %}" alt="" />
          </div>
        </div>
<!-- Main BLock -->
{% block content %} {% endblock %}
      </div>
    </div>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main-login.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

templates/employee_view/remote_work_request.html
{% extends 'employee_view/base.html' %} {% block content %}
<div class="container">
  <div class="row text-center">
    <div class="col-md-12">
      <!-- #TODO: -->
      <div id="alert-container"></div>

      <!-- Alerts -->
      {% include '_alerts.html' %}
      <form
        id="vacation-form"
        action="{% url 'remote_work_request'  %}"
        method="POST"
      >
        {% csrf_token %}
        <div class="alert-container"></div>
        <div class="form-group row">
          <label for="start_date" class="col-sm-2 col-form-label"
            >Start Date</label
          >
          <div class="col-sm-4">
            <div class="form-group">
              <div class="input-group date" id="startdate">
                <input
                  type="date"
                  class="form-control"
                  name="startdate"
                  required
                />
                <span class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
                </span>
              </div>
            </div>
          </div>
        </div>

        <div class="form-group row">
          <label for="enddate" class="col-sm-2 col-form-label">End Date</label>
          <div class="col-sm-4">
            <div class="form-group">
              <div class="input-group date" id="enddate">
                <input
                  type="date"
                  class="form-control"
                  name="enddate"
                  required
                />
                <span class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
                </span>
              </div>
            </div>
          </div>
        </div>

        <div class="form-group row">
          <label for="start_date" class="col-sm-2 col-form-label">Description</label>
          <div class="col-sm-4">
            <div class="form-group">
              <div class="input-group description" id="description">
                <input
                  type="text"
                  class="form-control"
                  name="description"
                  required
                />
              </div>
            </div>
          </div>
        </div>
        <button class="btn btn-secondary mt-4" type="submit">Save</button>
      </form>
    </div>
  </div>
</div>
{% endblock content %} {% block extrascripts %}
<script>
  $(document).ready(function () {
    // Function to check if the end date is after the start date
    function validateDates() {
      var startDate = new Date($("#startdate input").val());
      var endDate = new Date($("#enddate input").val());

      if (endDate < startDate) {
        $("#alert-container").html(
          '<div class="alert alert-danger">End date should be after the start date.</div>'
        );
        setTimeout(function () {
          $("#alert-container").html("");
        }, 2000);
        return false;
      } else {
        $("#alert-container").html(""); // Clear any previous error message
        return true;
      }
    }

    // Attach form submission event handler
    $("#vacation-form").submit(function (event) {
      if (!validateDates()) {
        event.preventDefault(); // Prevent form submission if dates are invalid
      }
    });
  });
</script>
{% endblock extrascripts %}

templates/employee_view/transfer_days_request.html
{% extends 'employee_view/base.html' %} {% block content %}
<div class="container">
  <div class="row text-center">
    <div class="col-md-12">
      <!-- #TODO: -->
      <div id="alert-container"></div>

      <!-- Alerts -->
      {% include '_alerts.html' %}
      <form
        id="vacation-form"
        action="{% url 'transfer_days_request'  %}"
        method="POST"
      >
        {% csrf_token %}
        <div class="alert-container"></div>
        <div class="form-group row">
          <label for="start_date" class="col-sm-2 col-form-label"
            >Start Date</label
          >
          <div class="col-sm-4">
            <div class="form-group">
              <div class="input-group date" id="startdate">
                <input
                  type="date"
                  class="form-control"
                  name="startdate"
                  required
                />
                <span class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
                </span>
              </div>
            </div>
          </div>
        </div>

        <div class="form-group row">
          <label for="enddate" class="col-sm-2 col-form-label">End Date</label>
          <div class="col-sm-4">
            <div class="form-group">
              <div class="input-group date" id="enddate">
                <input
                  type="date"
                  class="form-control"
                  name="enddate"
                  required
                />
                <span class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
                </span>
              </div>
            </div>
          </div>
        </div>

        <div class="form-group row">
          <label for="start_date" class="col-sm-2 col-form-label">Reason</label>
          <div class="col-sm-4">
            <div class="form-group">
              <div class="input-group description" id="description">
                <input
                  type="text"
                  class="form-control"
                  name="description"
                  required
                />
              </div>
            </div>
          </div>
        </div>
        <button class="btn btn-secondary mt-4" type="submit">Save</button>
      </form>
    </div>
  </div>
</div>
{% endblock content %} {% block extrascripts %}
<script>
  $(document).ready(function () {
    // Function to check if the end date is after the start date
    function validateDates() {
      var startDate = new Date($("#startdate input").val());
      var endDate = new Date($("#enddate input").val());

      if (endDate < startDate) {
        $("#alert-container").html(
          '<div class="alert alert-danger">End date should be after the start date.</div>'
        );
        setTimeout(function () {
          $("#alert-container").html("");
        }, 2000);
        return false;
      } else {
        $("#alert-container").html(""); // Clear any previous error message
        return true;
      }
    }

    // Attach form submission event handler
    $("#vacation-form").submit(function (event) {
      if (!validateDates()) {
        event.preventDefault(); // Prevent form submission if dates are invalid
      }
    });
  });
</script>
{% endblock extrascripts %}